
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 33;
  public static final int EGAL = 23;
  public static final int OU = 27;
  public static final int PLUS = 15;
  public static final int SUP = 21;
  public static final int LIRE = 7;
  public static final int ECR = 6;
  public static final int TANTQUE = 8;
  public static final int ALORS = 12;
  public static final int REPETER = 9;
  public static final int NON = 28;
  public static final int INF = 22;
  public static final int PARFER = 20;
  public static final int MOINS = 16;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 10;
  public static final int SINON = 13;
  public static final int TYPE = 29;
  public static final int MULT = 17;
  public static final int EOF = 0;
  public static final int EGALEGAL = 24;
  public static final int DIV = 18;
  public static final int CONSTANTEBOOL = 31;
  public static final int ET = 26;
  public static final int SI = 11;
  public static final int error = 1;
  public static final int PAROUV = 19;
  public static final int DIFF = 25;
  public static final int CONSTANTEINT = 30;
  public static final int DEBUT = 3;
  public static final int FINSI = 14;
  public static final int FIN = 4;
  public static final int CSTECHAINE = 32;
  public static final int PROGRAMME = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME",
  "DEBUT",
  "FIN",
  "POINTVIRGULE",
  "ECR",
  "LIRE",
  "TANTQUE",
  "REPETER",
  "FINTANTQUE",
  "SI",
  "ALORS",
  "SINON",
  "FINSI",
  "PLUS",
  "MOINS",
  "MULT",
  "DIV",
  "PAROUV",
  "PARFER",
  "SUP",
  "INF",
  "EGAL",
  "EGALEGAL",
  "DIFF",
  "ET",
  "OU",
  "NON",
  "TYPE",
  "CONSTANTEINT",
  "CONSTANTEBOOL",
  "CSTECHAINE",
  "IDF"
  };
}

